apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certifier-secrets-mgmt-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certifier-secrets-mgmt
subjects:
- kind: ServiceAccount
  name: cicd
  namespace: certifier
