apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: certifier-front-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    cert-manager.io/cluster-issuer: letsencrypt-freeverse
    external-dns.alpha.kubernetes.io/hostname: theprepco.gorengine.com

spec:
  tls:
  - hosts:
    - {{ .Values.certifierFrontHost }}
    secretName: certifier-front-tls
  rules:
  - host: {{ .Values.certifierFrontHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: certifier-front
            port:
              number: 80

