apiVersion: v1
kind: Service
metadata:
  name: certifier-front
  labels:
    app.kubernetes.io/app: certifier-front
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/app: certifier-front
